FROM python:3.10-slim-bullseye

WORKDIR /app

RUN apt-get update
RUN apt-get install -y build-essential git libffi-dev rustc libssl-dev cron libmagickwand-dev

COPY . .
RUN pip3 install -r requirements.txt --no-cache-dir

RUN crontab cron/cronjobs

CMD ["cron", "-f"]
