FROM python:3.10-slim-bullseye

WORKDIR /app

COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install -y build-essential git libffi-dev rustc libssl-dev cron
RUN pip3 install -r requirements.txt --no-cache-dir

COPY . .

RUN crontab cron/cronjobs

CMD ["cron", "-f"]
