apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huttusta-rotta-gt-cert
  namespace: huttustutka
spec:
  secretName: huttusta-rotta-gt-cert-secret
  commonName: 'huttusta.rotta.gt'
  dnsNames:
    - huttusta.rotta.gt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
