apiVersion: v1
kind: PersistentVolume
metadata:
  name: huttustutka-pv
  namespace: huttustutka
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - raspi2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huttustutka-pvc
  namespace: huttustutka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-path
